name: Online Shopping Platform CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  # =====================================================
  # BACKEND CI
  # Builds every Spring Boot microservice
  # =====================================================
  backend-build:

    name: Build Backend Services (${{ matrix.service }})

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service:
          - EurekaServer
          - ApiGateway
          - AuthService
          - ProductService
          - CartService
          - OrderService
          - PaymentService
          - NotificationService
          - AdminService

    steps:

      # Checkout project source code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install Java 17
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Give permission to Maven Wrapper on Linux
      - name: Make Maven Wrapper Executable
        working-directory: backend/${{ matrix.service }}
        run: chmod +x mvnw

      # Build Spring Boot service
      - name: Build ${{ matrix.service }}
        working-directory: backend/${{ matrix.service }}
        run: ./mvnw -B clean package -DskipTests


  # =====================================================
  # FRONTEND CI
  # Builds Angular frontend
  # =====================================================
  frontend-build:

    name: Build Angular Frontend

    runs-on: ubuntu-latest

    steps:

      # Checkout project source code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Display versions for debugging
      - name: Check Node and NPM Versions
        run: |
          node --version
          npm --version

      # Install Angular project dependencies
      - name: Install Dependencies
        working-directory: frontend
        run: npm install

      # Build Angular application
      - name: Build Angular Application
        working-directory: frontend
        run: npm run build
